### ISSUE TITLE
Dependency resolution problem

### ISSUE THREAD

**Issue by dizzystreak** [radiorabe/centos-rpm-motion#1]
`yum install motion` fails due to failed dependency resolutions.

Error: Package: motion-4.1.1-4.11.x86_64 (home_radiorabe_video)
           Requires: libavdevice.so.56(LIBAVDEVICE_56)(64bit)
Error: Package: motion-4.1.1-4.11.x86_64 (home_radiorabe_video)
           Requires: libavcodec.so.56()(64bit)
Error: Package: motion-4.1.1-4.11.x86_64 (home_radiorabe_video)
           Requires: libavdevice.so.56()(64bit)
Error: Package: motion-4.1.1-4.11.x86_64 (home_radiorabe_video)
           Requires: libavformat.so.56()(64bit)
Error: Package: motion-4.1.1-4.11.x86_64 (home_radiorabe_video)
           Requires: libavcodec.so.56(LIBAVCODEC_56)(64bit)
Error: Package: motion-4.1.1-4.11.x86_64 (home_radiorabe_video)
           Requires: libavformat.so.56(LIBAVFORMAT_56)(64bit)
Error: Package: motion-4.1.1-4.11.x86_64 (home_radiorabe_video)
           Requires: libavutil.so.54()(64bit)
Error: Package: motion-4.1.1-4.11.x86_64 (home_radiorabe_video)
           Requires: libswscale.so.3(LIBSWSCALE_3)(64bit)
Error: Package: motion-4.1.1-4.11.x86_64 (home_radiorabe_video)
           Requires: libavutil.so.54(LIBAVUTIL_54)(64bit)
Error: Package: motion-4.1.1-4.11.x86_64 (home_radiorabe_video)
           Requires: libswscale.so.3()(64bit)

**Comment by hairmare** [comment]
Motion depends on libavdevice which is not in CentOS. You can get if from various sources, I usually use the [Nux Dextop Repo](https://li.nux.ro/repos.html) but there might also be other sources.

```bash
yum install -y \
  epel-release \
  http://li.nux.ro/download/nux/dextop/el7/x86_64/nux-dextop-release-0-5.el7.nux.noarch.rpm

yum install -y \
  motion
```

**Comment by dizzystreak** [comment]
Thanks for the hint and README.md update.
